---
title: "Using CSV data with craftyr"
author: "Sascha Holzhauer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using raster data with craftyr}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---


# Input (read) CSV Data

## Features

	* Limit considered ticks by starttick, endtick, and interval
	* Read CSV files of multiple regions at once

## Source: Regional CSV data

```{r, eval=FALSE}
cdata <- input_csv_data(simp, dataname = NULL, datatype = "Cell", colums = "LandUseIndex",
		pertick = TRUE, starttick = 2010, endtick = 2040, tickinterval = 30, attachfileinfo = TRUE)
cdata <<- split(cdata, list(cdata$Tick,cdata$Runid))
csv_LandUseIndex_split <- cadata
input_tools_save(simp, "csv_LandUseIndex_split")
```

For large data sets it is a good idea to clean the data somewhat before storing:

```{r, eval=FALSE}
cdata <- input_csv_data(simp, dataname = NULL, datatype = "Cell", colums = "LandUseIndex",
		pertick = TRUE, starttick = 2010, endtick = 2040, tickinterval = 30, attachfileinfo = TRUE)

cdata$Region <- NULL
cdata$Scenario <- NULL

cdata <- split(cdata, list(cdata$Tick,cdata$Runid))

cdata <- lapply(cdata, function(x) {x$Runid <- NULL; x})
cdata <- lapply(cdata, function(x) {x$Tick <- NULL; x})

csv_LandUseIndex_split <- cadata
input_tools_save(simp, "csv_LandUseIndex_split")
rm(list(csv_LandUseIndex_split, cdata)
```


# Visualise CSV Data

## Map Data

### LandUseIndex

```{r, eval=FALSE}
input_tools_load(simp, "csv_LandUseIndex_split")
cdata <- csv_LandUseIndex_split
cdata$"2010.2"$ID <<- as.factor("Homo_2010")
cdata$"2040.2"$ID <<- as.factor("Homo_2040")

diffcells <<- cdata$"2010.2"
diffcells$LandUseIndex <<- NA
diffhomo$LandUseIndex[cdata$"2040.2"$LandUseIndex - cdata$"2010.2"$LandUseIndex != 0] <- 3
diffhomo$ID <- as.factor("Diff_Homo_2040-2010")

toplot <- list(cdata$"2010.2", cdata$"2040.2", diffhomo)
rm(diffhomo)
rm(cdata)
visualise_cells_printPlots(simp, toplot, idcolumn = "ID",
		title = "EU-Homo", legendtitle = "AFTs",
		factorial= TRUE, omitaxisticks = TRUE, ncol = 3,
		legenditemnames = simp$mdata$aftNames, coloursetname="AFT")
```
