---
title: "Using raster data with craftyr"
author: "Sascha Holzhauer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using raster data with craftyr}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---


# Input (read) Raster Data

## Features

	* Limit considered ticks by starttick, endtick, and interval
	* Read raster files of multiple regions at once

## Source: Regional Raster Data

### LandUseIndex

```{r, eval=TRUE, results="hide"}
library(craftyr)
simp <- param_getExamplesSimp()
raster_landUseIndex <- input_raster_output(simp,
		datatype = "Agent", 
		dataname = "SerialID",
		starttick = 2010)
names(raster_landUseIndex) <- simp$sim$rundesc
input_tools_save(simp, "raster_landUseIndex")
```

# Visualise Raster Data

## Maps

## Aggregate Data

## LandUseIndex: Timeline
```{r, eval=TRUE, results="hide"}
input_tools_load(simp, "raster_landUseIndex")
```
```{r, eval=TRUE, fig.width=7}
landUseIndexData <- convert_raster_getAftNumbers(raster_landUseIndex)
landUseIndexData$AFT <- factor(landUseIndexData$AFT)
visualise_lines(simp, landUseIndexData, "Value", title = "Total AFT composition",
		colour_column = "AFT",
		colour_legenditemnames = simp$mdata$aftNames,
		linetype_column = "Runid",
		linetype_legendtitle = simp$sim$rundesclabel,
		linetype_legenditemnames = simp$sim$rundesc,
		filename = paste("TotalAftComposition", 
				shbasic::shbasic_condenseRunids(data.frame(aftData)[, "ID"]), sep="_"),
		alpha=0.7)
```