---
title: "Create and adjust CRAFTY configuration files"
author: "Sascha Holzhauer"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
  toc: true
vignette: >
  %\VignetteIndexEntry{Create and adjust CRAFTY configuration files}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

		
# Manipulate CSV files

## Explore number of cells of regions (from capital CSV files)

```{r, eval=FALSE, results="hide"}
library(craftyr)
simp <- craftyr::param_getDefaultSimp()
simp$sim$filepartorder	<- c("regionalisation", "U", "regions", "U", "datatype")
cellnumdf <- input_csv_param_capitals_cellnumbers(simp = simp, 
			regionpartfromend = 2, regionpartdevider = "_")
# order decreasingly according to number of cells:
cellnumdf[order(cellnumdf, decreasing = TRUE)]
```

## Determine assignment to slots for parallel computing

```{r, eval=FALSE, results="hide"}
library(craftyr)
simp <- craftyr::param_getDefaultSimp()
simp$sim$filepartorder	<- c("regionalisation", "U", "regions", "U", "datatype")
slotgroups <- input_csv_param_capitals_slotassignment(simp = simp, slotnums = 16,
			regionpartfromend = 2, regionpartdevider = "_")
```

## Change column headers

```{r, eval=FALSE, results="hide"}
library(craftyr)
simp <- craftyr::param_getDefaultSimp()
simp$sim$folder 	<- ""
adjust_changecolumnnames(simp,  indir = simp$dirs$param$getparamdir(simp, "capitals"),
		colname_old = "Pasture", colname_new = "Grass", filepattern = "*.csv")
```

# Further scripts

There are a number of python scripts which might be helpful for configuring CRAFTY, too:
https://bitbucket.org/S-Holzhauer/py4abm